---
repos:
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.17.2
    hooks:
      - id: ansible-lint
  - repo: https://github.com/igorshubovych/markdownlint-cli.git
    rev: v0.35.0
    hooks:
      - id: markdownlint
