---
namespace: lab
name: aws_infrastructure_config_demos
version: 3.0.0
readme: README.md
authors:
  - Scott Harwell <sharwell@redhat.com>
description: AWS use cases in the Ansible Cloud Content Incubation program.
license:
  - GPL-3.0-or-later
license_file: "LICENSE"
tags:
  - "cloud"
  - "aws"
dependencies:
  amazon.aws: ">=6.2.0"
  amazon.cloud: ">=0.4.0"
  community.aws: ">=6.1.0"
repository: https://github.com/ansible-content-lab/aws.infrastructure_config_demos
documentation: https://github.com/ansible-content-lab/aws.infrastructure_config_demos
homepage: https://github.com/ansible-content-lab/aws.infrastructure_config_demos
issues: https://github.com/ansible-content-lab/aws.infrastructure_config_demos/issues
build_ignore:
  - ".tox"
  - ".git"
  - ".github"
  - ".gitignore"
