---
aws_region: us-east-1
aws_bucket_prefix: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID')[1:5] | lower }}"
aws_bucket_name: "{{ aws_bucket_prefix }}-reports"
aws_bucket_permissions: public-read
aws_report: vpc
aws_instance_filters: "{{ omit }}"
