---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Test peer_transit_networks role
      ansible.builtin.include_tasks:
        file: tasks/peer_transit_networks.yml
        apply:
          tags:
            - peer_transit_networks
      tags:
        - always
