---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Test transit_peered_networks role
      ansible.builtin.include_tasks:
        file: tasks/transit_peered_networks.yml
        apply:
          tags:
            - transit_peered_networks
      tags:
        - always
