---
- name: create report bucket
  amazon.aws.s3_bucket:
    name: "{{ aws_bucket_name }}"
    region: "{{ aws_region }}"
    state: present
    acl: "{{ aws_bucket_permissions }}"

- name: configure bucket for website
  community.aws.s3_website:
    name: "{{ aws_bucket_name }}"
    state: present

- name: put index.html
  amazon.aws.s3_object:
    bucket: "{{ aws_bucket_name }}"
    object: index.html
    src: files/index.html
    mode: put
    permission: "{{ aws_bucket_permissions }}"
  register: bucket_put

- debug:
    msg: "{{ bucket_put }}"
