---

- name: create report bucket
  amazon.aws.s3_bucket:
    name: "{{ aws_bucket_name }}"
    region: "{{ aws_region }}"
    state: present
    acl: "{{ aws_bucket_permissions }}"

- name: configure bucket for website
  community.aws.s3_website:
    name: "{{ aws_bucket_name }}"
    state: present

- name: Include tasks
  ansible.builtin.include_tasks: "vpc.yml"

- name: put website files
  community.aws.s3_sync:
    bucket: "{{ aws_bucket_name }}"
    file_root: ../files

- name: put vpc-report
  amazon.aws.s3_object:
    bucket: "{{ aws_bucket_name }}"
    object: vpc-report.html
    content: "{{ lookup('template', 'vpc_report.j2')}}"
    mode: put
    permission: "{{ aws_bucket_permissions }}"
    metadata: 'Content-Type=text/html'

- name: put index.html
  amazon.aws.s3_object:
    bucket: "{{ aws_bucket_name }}"
    object: index.html
    src: files/index.html
    mode: put
    permission: "{{ aws_bucket_permissions }}"

- debug:
    msg: "Bucket URL: http://{{ aws_bucket_name }}.s3-website.{{ aws_region }}.amazonaws.com"
