---

- name: create report bucket
  amazon.aws.s3_bucket:
    name: "{{ aws_bucket_name }}"
    region: "{{ aws_region }}"
    state: present
    acl: "{{ aws_bucket_permissions }}"

- name: configure bucket for website
  community.aws.s3_website:
    name: "{{ aws_bucket_name }}"
    state: present

- name: Include tasks
  ansible.builtin.include_tasks: "vpc.yml"

- name: find website files
  ansible.builtin.find:
    paths: files
    recurse: yes
  register: web_files

- name: put website files
  amazon.aws.s3_object:
    bucket: "{{ aws_bucket_name }}"
    object: /
    src: ../files
    mode: put
    permission: "{{ aws_bucket_permissions }}"

- name: put vpc_report
  amazon.aws.s3_object:
    bucket: "{{ aws_bucket_name }}"
    object: vpc_report.html
    src: "{{ lookup('template', 'vpc_report.j2')}}"
    mode: put
    permission: "{{ aws_bucket_permissions }}"

- name: put index.html
  amazon.aws.s3_object:
    bucket: "{{ aws_bucket_name }}"
    object: index.html
    src: files/index.html
    mode: put
    permission: "{{ aws_bucket_permissions }}"

- debug:
    msg: "Bucket URL: http://{{ aws_bucket_name }}.s3-website.{{ aws_region }}.amazonaws.com"
