---
- name: retrieve vpc information
  amazon.aws.ec2_vpc_net_info:
    region: "{{ aws_region }}"
  register: vpc_info

- name: retrieve info for ec2 instances
  amazon.aws.ec2_instance_info:
    region: "{{ aws_region }}"
  register: ec2_instance_info

- name: Gather information about Internet Gateways IGWs
  amazon.aws.ec2_vpc_igw_info:
    region: "{{ aws_region }}"
  register: igw_info

- name: grab information about AWS user
  amazon.aws.aws_caller_info:
    region: "{{ aws_region }}"
  register: whoami
