---
- name: retrieve vpc information
  amazon.aws.ec2_vpc_net_info:
    region: "{{ aws_region }}"
  register: vpc_info

- name: retrieve info for ec2 instances
  amazon.aws.ec2_instance_info:
    region: "{{ aws_region }}"
  register: ec2_instance_info

- name: Gather information about Internet Gateways IGWs
  amazon.aws.ec2_vpc_igw_info:
    region: "{{ aws_region }}"
  register: igw_info

- name: grab information about AWS user
  amazon.aws.aws_caller_info:
    region: "{{ aws_region }}"
  register: whoami

- name: save username of AWS user
  ansible.builtin.set_fact:
    aws_user: '{{ whoami.arn.split("/")[-1] }}'
    py_cmd: >-
      {{ lookup('pipe', ansible_playbook_python ~ ' -c "import boto3; print(boto3.__version__)"') }}

- name: put vpc-report
  amazon.aws.s3_object:
    bucket: "{{ aws_bucket_name }}"
    object: vpc-report.html
    content: "{{ lookup('template', 'vpc_report.j2')}}"
    mode: put
    permission: "{{ aws_bucket_permissions }}"
    metadata: 'Content-Type=text/html'
