---
- name: Create and publish AWS cloud reports
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    reports_aws_report: tags
  tasks:
    - name: Include reports role
      ansible.builtin.include_role:
        name: lab.aws_infrastructure_config_demos.reports
